server:
  port: 8081

spring:
  datasource:
#    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:~/testdb
    url: jdbc:h2:file:./src/db/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false
  h2:
    console:
      path: /h2-console
      enabled: true

logging:
  level:
    org:
      hibernate: INFO

project:
  security:
    responseType: JSON